### PR TITLE
Add proper typing to vsrepo with MyPy

### PR DESCRIPTION
**Pull request by RivenSkaye**
This adds proper typehints and passes typechecking with MyPy. That's a good thing because it means type safety in a dynamically typed language.
It also makes it easier to see where errors originate from.
Besides that I did some generic cleanup like removing unused imports and preventing re-assigning to a variable immediately after assigning an initial value wherever this could be prevented.

### CODE REVIEW

**Comment by RivenSkaye** [comment]
These changes have been tried and tested btw, they all work on my system

**Comment by myrsloik** [comment]
They don't change required python versions or anything like that?

**Comment by RivenSkaye** [comment]
None of that whatsoever. I made all of the typing compatible with pre-3.10 Python versions.
The only thing 3.10 adds is alternative syntax for Optionals and Unions, where you can just specify `typeA | typeB | None` which looks cleaner

**Comment by RivenSkaye** [comment]
Hold up, wait with the merge, I broke something

**Pull request merged**
