### PR TITLE
Update mvsfunc, muvsfunc, kagefunc, fvsfunc; Fix xvs; Upload lvsfunc, faggotDb

### PR DESCRIPTION
**Pull request by OrangeChannel**
I'm not sure if I did this right, nor do I know how to test if it worked. Specifically,  not sure if the dependency list works with naming on the new lvsfunc.json

### CODE REVIEW

**Comment by theChaosCoder** [comment]
This `"github": "https://gist.github.com/AlucardSama04/8b48f8355597bc890d6622f207661c71",` causes problems with vsrupdate.py -g since it is not a "github url".

**Comment by OrangeChannel** [comment]
I contacted AlucardSama04 and had them move it to a new repository. Link should be fixed.

**Comment by myrsloik** [comment]
Not a single hash correct. This goes off to the junk pile because I don't have time to fix it.

**Comment by theChaosCoder** [comment]
@OrangeChannel How did you calc the hashes? I always let vsrepo do it. 
**vsrupdate.py compile**
after that just install with portable paramtere like this **vsrepo.py -p install xyz**. This way you test your package and see the correct hash.

**Pull request merged**
