### PR TITLE
Add Descale

### PR DESCRIPTION
**Pull request by theChaosCoder**
Special case: plugin and pyscript in one zip file. How to deal with it?
This works though.

### CODE REVIEW

**Comment by myrsloik** [comment]
This one is a mess... will think about what to do. In all other cases the script wasn't named the same as the plugin.

**Comment by myrsloik** [comment]
It kinda works out as is, I'll keep it in the current state until I figure out something better.

**Comment by theChaosCoder** [comment]
Maybe allow something like this:
```
"type": "Plugin",
"releases": [{
		"version": "r2",
"win64": {
			"url": "https://github.com/Irrational-Encoding-Wizardry/vapoursynth-descale/releases/download/r2/vapoursynth-descale-r2-win64.zip",
			"files": ["libdescale.dll"],
			"hash": { "libdescale.dll": "85448072bbb05e63dbd6a845a0331f05ef528c88" }
		},
"script": {
			"url": "https://github.com/Irrational-Encoding-Wizardry/vapoursynth-descale/releases/download/r2/vapoursynth-descale-r2-win64.zip",
			"files": ["descale.py"],
			"hash": { "descale.py": "cd8528ccd075beeb9bc308c9f2d725a1d21bc20f" }
		}
```
Now in this case url in scripts is ofc redundant.
But this could be seen as a plugin script combo. I don't know if you saw this, but mvtools-sf has also a helper script https://github.com/IFeelBloated/vapoursynth-mvtools-sf/blob/master/src/mvmulti.py

It's not a dependency, but it's kinda part of the plugin and you basically want to use it.


It's just an idea which will hopefully lead to even better ideas :)

**Comment by myrsloik** [comment]
Derp, I missed mvmulti since it's not in the release file. I'm thinking about a way to improve it things which would require a small json revision. For example the files and hash parts are trivially combinable if you think about it.
I'll probably do what you suggest and allow plugins to also have a "script" section but it may take a bit until I get around to it.

**Comment by theChaosCoder** [comment]
Just to confuse you even more. Bm3d has also an "easy to use script" in mvsfunc. Should mvsfunc also be downloaded if one installs bm3d?

**Comment by myrsloik** [comment]
No, only strict dependencies. It's not part of the same package.

**Pull request merged**
