### PR TITLE
Add fvsfunc, muvsfunc, nnedi3_rpow2

### PR DESCRIPTION
**Pull request by theChaosCoder**

### CODE REVIEW

**Comment by theChaosCoder** [comment]
Note the "version": "git:cd6a442" in fvs and muv since there is no official release

**Comment by theChaosCoder** [comment]
Theoretically muvsfunc still has 2 missing dependencies vsfm.TextSubMod  vsf.TextSub

**Comment by myrsloik** [comment]
I guess those can be added later... You are planning to create packages for them, right?

**Comment by theChaosCoder** [comment]
done

**Pull request merged**
