### PR TITLE
Adds an script that can generate stubs for typecheckers and IDEs

### PR DESCRIPTION
**Pull request by stuxcrystal**
`.pyi`-files are special files that IDEs and Type-Checkers use for type-checking and autocompletion.

See this video to see why this is useful:
https://f.nemur.in/file/stux-sharex/ShareX/2020/05/2020-05-13_14-27-14.mp4 (At this time the script was called `vsgenpyi.py`.)

Usage:
```
usage: vsgenstubs.py [-h] [--plugin PLUGIN] [--avs-plugin AVS_PLUGIN] [--output OUTPUT]
                      [--pyi-template PYI_TEMPLATE]

optional arguments:
  -h, --help            show this help message and exit
  --plugin PLUGIN, -p PLUGIN
                        Also include manually added plugin
  --avs-plugin AVS_PLUGIN
                        Also include manually added AviSynth plugin.
  --output OUTPUT, -o OUTPUT
                        Where to output the file. The special value '-' means output to stdout.
  --pyi-template PYI_TEMPLATE
                        Don't use unless you know what you are doing.
```

### CODE REVIEW

**Comment by myrsloik** [comment]
Interesting if it can be automated that much. But how does it fit into the rest? vsrepo should automatically run it on the main plugin dlls after install?

**Comment by stuxcrystal** [comment]
This can be a good idea. However, I think we can do that in a second step.

**Comment by stuxcrystal** [comment]
I did some tests with several Editors and IDEs.

TL,DR: Automating generating a `pyi`-file into the `site-packages` folders in vsrepo is essentially useless as only one IDE actually read this. All Editors read `vapoursynth.pyi`-file if it was inside the project root directory.

1. *PyCharm* from JetBrains
   PyCharm was the only IDE that actually seemed to read a `vapoursynth.pyi` from `site-packages`
2. *Visual Studio Code* from Microsoft
   VSCode only supported `.pyi`-files if it was in project-root and only if the .NET-Based Language Server was active (`"python.jediEnabled": false`). There are reports that additional settings made it read the `pyi`-file from `site-packages` but I did not test it.
3. *Visual Studio* from Microsoft
  Visual Studio only supported `.pyi`-files if it was in project-root.
4. *Sublime Text*
   Sublime Text only supported `.pyi`-files if it was in project-root. In default configuration it also dumped all possible parameters into your file when typing `(`.
5. *Atom*
   Did not get auto-completions to work within 5 minutes of googling.

Therefore, I think the best course of action is keeping `vsgenstubs.py` as a separate script that dumps a `vapoursynth.pyi` into the current directory.

**Comment by stuxcrystal** [comment]
I refined the template and the generated "Plugin"-Classes to play better with mypy. Thanks for @heicrd for helping.

**Pull request merged**
